# .pre-commit-config.yaml
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.0          # עדכנו לגרסה האחרונה
    hooks:
      - id: ruff         # linter
      - id: ruff-format  # formatter
      